<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="ClientServiceImplService" targetNamespace="http://impl.ws.t2no1.esi/" xmlns:ns1="http://service.ws.t2no1.esi/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.ws.t2no1.esi/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="http://176.34.224.194:8080/ws/clientService?wsdl=ClientService.wsdl" namespace="http://service.ws.t2no1.esi/">
    </wsdl:import>
  <wsdl:binding name="ClientServiceImplServiceSoapBinding" type="ns1:ClientService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getContract">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getContract">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getContractResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="createContract">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="createContract">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="createContractResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ClientServiceImplService">
    <wsdl:port binding="tns:ClientServiceImplServiceSoapBinding" name="ClientServiceImplPort">
      <soap:address location="http://176.34.224.194:8080/ws/clientService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>